// <auto-generated />
using System;
using DeslandesApp.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeslandesApp.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260315171255_PessoaHistorico")]
    partial class PessoaHistorico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("Cep")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CEP");

                    b.Property<string>("Complemento")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOA_ID");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("LOCALIDADE");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("LOGRADOURO");

                    b.Property<string>("Numero")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NUMERO");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("UF");

                    b.HasKey("Id");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("ENDERECO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.FailedLoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDFAILEDLOGINATTEMPT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAHORA");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDUSUARIO");

                    b.Property<string>("IpAcesso")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IPACESSO");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("MENSAGEM");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("USERAGENT");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("FAILEDLOGINATTEMPTS", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Fotos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("FotoNome")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("FOTONOME");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasFilter("[USUARIO_ID] IS NOT NULL");

                    b.ToTable("FOTOS", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoNiveis", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNivel")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuario", "IdNivel");

                    b.HasIndex("IdNivel");

                    b.ToTable("GRUPONIVEL", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoSetores", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSetor")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuario", "IdSetor");

                    b.HasIndex("IdSetor");

                    b.ToTable("GRUPOSETORES", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.InformacoesComplementares", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Comentario")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("COMENTARIO");

                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOA_ID");

                    b.Property<string>("TIPOPESSOA")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("INFORMACOESCOMPLEMENTARES", (string)null);

                    b.HasDiscriminator<string>("TIPOPESSOA").HasValue("InformacoesComplementares");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.LoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraAcesso")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAcesso")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("IPACESSO");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("MENSAGEM");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("bit");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("USERAGENT");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LOGINHISTORY", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Niveis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeNivel")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMENIVEL");

                    b.HasKey("Id");

                    b.ToTable("NIVEL", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apelido")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("APELIDO");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<int?>("Etiqueta")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdSexo")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SEXO_ID");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOME");

                    b.Property<int?>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("TIPO")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("TipoEmail")
                        .HasColumnType("int");

                    b.Property<int?>("TipoTelefone")
                        .HasColumnType("int");

                    b.Property<string>("ValorEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAIL");

                    b.HasKey("Id");

                    b.HasIndex("IdSexo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("PESSOA", (string)null);

                    b.HasDiscriminator<string>("TIPO").HasValue("Pessoa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DadosAntes")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("DADOSANTES");

                    b.Property<string>("DadosDepois")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("DADOSDEPOIS");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAALTERACAO");

                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOA_ID");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("OBSERVACOES");

                    b.HasKey("Id");

                    b.HasIndex("IdPessoa");

                    b.HasIndex("IdUsuario");

                    b.ToTable("PESSOA_HISTORICO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeSetor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NOMESETOR");

                    b.HasKey("Id");

                    b.ToTable("SETORES", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Sexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeSexo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOMESEXO");

                    b.HasKey("Id");

                    b.HasIndex("NomeSexo")
                        .IsUnique();

                    b.ToTable("SEXO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("NomeUsuario")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("SENHA");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("ValorEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAIL");

                    b.HasKey("Id");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.InformacoesComplementaresPessoaFisica", b =>
                {
                    b.HasBaseType("DeslandesApp.Domain.Models.Entities.InformacoesComplementares");

                    b.Property<string>("AtividadeEconomica")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ATIVIDADEECONOMICA");

                    b.Property<string>("DataNascimento")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("DATANASCIMENTO");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ESTADOCIVIL");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NACIONALIDADE");

                    b.Property<string>("Naturalidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NATURALIDADE");

                    b.Property<string>("NomeEmpresa")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("NomeMae")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEMAE");

                    b.Property<string>("NomePai")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEPAI");

                    b.Property<string>("Profissao")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("PROFISSAO");

                    b.ToTable("INFORMACOESCOMPLEMENTARES");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.InformacoesComplementaresPessoaJuridica", b =>
                {
                    b.HasBaseType("DeslandesApp.Domain.Models.Entities.InformacoesComplementares");

                    b.Property<string>("Agencia")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("AGENCIA");

                    b.Property<string>("Cargo")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CARGO");

                    b.Property<string>("Contato")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CONTATO");

                    b.Property<string>("NomeBanco")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEBANCO");

                    b.Property<string>("NumeroConta")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NUMEROCONTA");

                    b.Property<string>("Pix")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PIX");

                    b.Property<int?>("TipoConta")
                        .HasColumnType("int")
                        .HasColumnName("TIPOCONTA");

                    b.ToTable("INFORMACOESCOMPLEMENTARES");

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaFisica", b =>
                {
                    b.HasBaseType("DeslandesApp.Domain.Models.Entities.Pessoa");

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("CarteiraTrabalho")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("CertidaoReservista")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Passaporte")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("PisPasep")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("TituloEleitor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.ToTable("PESSOA");

                    b.HasDiscriminator().HasValue("PESSOAFISICA");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaJuridica", b =>
                {
                    b.HasBaseType("DeslandesApp.Domain.Models.Entities.Pessoa");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("InscricaoMunicipal")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("SimplesNacional")
                        .HasColumnType("int");

                    b.ToTable("PESSOA");

                    b.HasDiscriminator().HasValue("PESSOAJURIDICA");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Endereco", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithOne("Endereco")
                        .HasForeignKey("DeslandesApp.Domain.Models.Entities.Endereco", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.FailedLoginAttempt", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Fotos", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithOne("Fotos")
                        .HasForeignKey("DeslandesApp.Domain.Models.Entities.Fotos", "IdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoNiveis", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Niveis", "Niveis")
                        .WithMany("GrupoNiveis")
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany("GrupoNiveis")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Niveis");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoSetores", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Setor", "Setor")
                        .WithMany("GrupoSetores")
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany("GrupoSetores")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.InformacoesComplementares", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithOne("InformacoesComplementares")
                        .HasForeignKey("DeslandesApp.Domain.Models.Entities.InformacoesComplementares", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.LoginHistory", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Pessoa", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Sexo", "Sexo")
                        .WithMany("Pessoa")
                        .HasForeignKey("IdSexo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany("Pessoa")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sexo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaHistorico", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PessoaHistorico_Pessoa");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PessoaHistorico_Usuario");

                    b.Navigation("Pessoa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Niveis", b =>
                {
                    b.Navigation("GrupoNiveis");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Pessoa", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("InformacoesComplementares");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Setor", b =>
                {
                    b.Navigation("GrupoSetores");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Sexo", b =>
                {
                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("GrupoNiveis");

                    b.Navigation("GrupoSetores");

                    b.Navigation("Pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
