// <auto-generated />
using System;
using DeslandesApp.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeslandesApp.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260317170744_CorrecaoDosRelacionamentos")]
    partial class CorrecaoDosRelacionamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Acao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("NomeAcao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NOMEACAO");

                    b.HasKey("Id")
                        .HasName("PK_ACAO");

                    b.ToTable("ACAO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Bairro")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("Cep")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CEP");

                    b.Property<string>("Complemento")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOA_ID");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("LOCALIDADE");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("LOGRADOURO");

                    b.Property<string>("Numero")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NUMERO");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("UF");

                    b.HasKey("Id")
                        .HasName("PK_ENDERECO");

                    b.HasIndex("IdPessoa")
                        .IsUnique()
                        .HasDatabaseName("IX_ENDERECO_PESSOA_ID");

                    b.ToTable("ENDERECO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.FailedLoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDFAILEDLOGINATTEMPT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAHORA");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDUSUARIO");

                    b.Property<string>("IpAcesso")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IPACESSO");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("MENSAGEM");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("USERAGENT");

                    b.HasKey("Id")
                        .HasName("PK_FAILEDLOGINATTEMPTS");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_FAILEDLOGINATTEMPTS_IDUSUARIO");

                    b.ToTable("FAILEDLOGINATTEMPTS", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Foro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("NomeForo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NOMEFORO");

                    b.HasKey("Id")
                        .HasName("PK_FORO");

                    b.ToTable("FORO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Fotos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("FILEURL");

                    b.Property<string>("FotoNome")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("FOTONOME");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id")
                        .HasName("PK_FOTOS");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("IX_FOTOS_USUARIO_ID")
                        .HasFilter("[USUARIO_ID] IS NOT NULL");

                    b.ToTable("FOTOS", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoEnvolvidos", b =>
                {
                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDPESSOA");

                    b.Property<Guid>("IdProcesso")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDPROCESSO");

                    b.Property<Guid>("IdQualificacao")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDQUALIFICACAO");

                    b.HasKey("IdPessoa", "IdProcesso", "IdQualificacao")
                        .HasName("PK_GRUPOENVOLVIDOS");

                    b.HasIndex("IdProcesso")
                        .HasDatabaseName("IX_GRUPOENVOLVIDOS_IDPROCESSO");

                    b.HasIndex("IdQualificacao")
                        .HasDatabaseName("IX_GRUPOENVOLVIDOS_IDQUALIFICACAO");

                    b.ToTable("GRUPOENVOLVIDOS");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoNiveis", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDUSUARIO");

                    b.Property<Guid>("IdNivel")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDNIVEL");

                    b.HasKey("IdUsuario", "IdNivel")
                        .HasName("PK_GRUPONIVEL");

                    b.HasIndex("IdNivel")
                        .HasDatabaseName("IX_GRUPONIVEL_IDNIVEL");

                    b.ToTable("GRUPONIVEL", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoPessoaClientes", b =>
                {
                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDPESSOA");

                    b.Property<Guid>("IdProcesso")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDPROCESSO");

                    b.Property<Guid>("IdQualificacao")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDQUALIFICACAO");

                    b.HasKey("IdPessoa", "IdProcesso", "IdQualificacao")
                        .HasName("PK_GRUPOPESSOACLIENTES");

                    b.HasIndex("IdProcesso")
                        .HasDatabaseName("IX_GRUPOPESSOACLIENTES_IDPROCESSO");

                    b.HasIndex("IdQualificacao")
                        .HasDatabaseName("IX_GRUPOPESSOACLIENTES_IDQUALIFICACAO");

                    b.ToTable("GRUPOPESSOACLIENTES");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoSetores", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDUSUARIO");

                    b.Property<Guid>("IdSetor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDSETOR");

                    b.HasKey("IdUsuario", "IdSetor")
                        .HasName("PK_GRUPOSETORES");

                    b.HasIndex("IdSetor")
                        .HasDatabaseName("IX_GRUPOSETORES_IDSETOR");

                    b.ToTable("GRUPOSETORES", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.InformacoesComplementares", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Comentario")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("COMENTARIO");

                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOA_ID");

                    b.Property<string>("TIPOPESSOA")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("TIPOPESSOA");

                    b.HasKey("Id")
                        .HasName("PK_INFORMACOESCOMPLEMENTARES");

                    b.HasIndex("IdPessoa")
                        .IsUnique()
                        .HasDatabaseName("IX_INFORMACOESCOMPLEMENTARES_PESSOA_ID");

                    b.ToTable("INFORMACOESCOMPLEMENTARES", (string)null);

                    b.HasDiscriminator<string>("TIPOPESSOA").HasValue("InformacoesComplementares");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.LoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataHoraAcesso")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAHORAACESSO");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDUSUARIO");

                    b.Property<string>("IpAcesso")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("IPACESSO");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("MENSAGEM");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("bit")
                        .HasColumnName("SUCESSO");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("USERAGENT");

                    b.HasKey("Id")
                        .HasName("PK_LOGINHISTORY");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_LOGINHISTORY_IDUSUARIO");

                    b.ToTable("LOGINHISTORY", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Niveis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("NomeNivel")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMENIVEL");

                    b.HasKey("Id")
                        .HasName("PK_NIVEL");

                    b.ToTable("NIVEL", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Apelido")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("APELIDO");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<int?>("Etiqueta")
                        .HasColumnType("int")
                        .HasColumnName("ETIQUETA");

                    b.Property<Guid?>("IdSexo")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SEXO_ID");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOME");

                    b.Property<int?>("Perfil")
                        .HasColumnType("int")
                        .HasColumnName("PERFIL");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("SITE");

                    b.Property<string>("TIPO")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("TIPO");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("TELEFONE");

                    b.Property<int?>("TipoEmail")
                        .HasColumnType("int")
                        .HasColumnName("TIPOEMAIL");

                    b.Property<string>("ValorEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAIL");

                    b.HasKey("Id")
                        .HasName("PK_PESSOA");

                    b.HasIndex("IdSexo")
                        .HasDatabaseName("IX_PESSOA_SEXO_ID");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_PESSOA_USUARIO_ID");

                    b.ToTable("PESSOA", (string)null);

                    b.HasDiscriminator<string>("TIPO").HasValue("Pessoa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("DadosAntes")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("DADOSANTES");

                    b.Property<string>("DadosDepois")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("DADOSDEPOIS");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAALTERACAO");

                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOA_ID");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("OBSERVACOES");

                    b.HasKey("Id")
                        .HasName("PK_PESSOAHISTORICO");

                    b.HasIndex("IdPessoa")
                        .HasDatabaseName("IX_PESSOAHISTORICO_PESSOA_ID");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_PESSOAHISTORICO_USUARIO_ID");

                    b.ToTable("PESSOAHISTORICO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Processo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<int?>("Acesso")
                        .HasColumnType("int")
                        .HasColumnName("ACESSO");

                    b.Property<DateTime?>("Distribuido")
                        .HasColumnType("datetime2")
                        .HasColumnName("DISTRIBUIDO");

                    b.Property<int?>("Etiqueta")
                        .HasColumnType("int")
                        .HasColumnName("ETIQUETA");

                    b.Property<Guid?>("IdAcao")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDACAO");

                    b.Property<Guid?>("IdForo")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDFORO");

                    b.Property<int?>("Instancia")
                        .HasColumnType("int")
                        .HasColumnName("INSTANCIA");

                    b.Property<string>("Juizo")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("JUIZO");

                    b.Property<string>("LinkTribunal")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("LINKTRIBUNAL");

                    b.Property<string>("NumeroProcesso")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NUMEROPROCESSO");

                    b.Property<string>("Objeto")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("OBJETO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<string>("Pasta")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("PASTA");

                    b.Property<string>("Responsavael")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("RESPONSAVAEL");

                    b.Property<string>("Titulo")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("TITULO");

                    b.Property<decimal?>("ValorCausa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALORCAUSA");

                    b.Property<decimal?>("ValorCondenacao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALORCONDENACAO");

                    b.Property<string>("Vara")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("VARA");

                    b.HasKey("Id")
                        .HasName("PK_PROCESSO");

                    b.HasIndex("IdAcao")
                        .HasDatabaseName("IX_PROCESSO_IDACAO");

                    b.HasIndex("IdForo")
                        .HasDatabaseName("IX_PROCESSO_IDFORO");

                    b.ToTable("PROCESSO");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Qualificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("NomeQualificacao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NOMEQUALIFICACAO");

                    b.HasKey("Id")
                        .HasName("PK_QUALIFICACAO");

                    b.ToTable("QUALIFICACAO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("NomeSetor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NOMESETOR");

                    b.HasKey("Id")
                        .HasName("PK_SETORES");

                    b.ToTable("SETORES", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Sexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("NomeSexo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOMESEXO");

                    b.HasKey("Id")
                        .HasName("PK_SEXO");

                    b.HasIndex("NomeSexo")
                        .IsUnique()
                        .HasDatabaseName("IX_SEXO_NOMESEXO");

                    b.ToTable("SEXO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("NomeUsuario")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEUSUARIO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("SENHA");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("ValorEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAIL");

                    b.HasKey("Id")
                        .HasName("PK_USUARIOS");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.InformacoesComplementaresPessoaFisica", b =>
                {
                    b.HasBaseType("DeslandesApp.Domain.Models.Entities.InformacoesComplementares");

                    b.Property<string>("AtividadeEconomica")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ATIVIDADEECONOMICA");

                    b.Property<string>("DataNascimento")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("DATANASCIMENTO");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ESTADOCIVIL");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NACIONALIDADE");

                    b.Property<string>("Naturalidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NATURALIDADE");

                    b.Property<string>("NomeEmpresa")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEEMPRESA");

                    b.Property<string>("NomeMae")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEMAE");

                    b.Property<string>("NomePai")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEPAI");

                    b.Property<string>("Profissao")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("PROFISSAO");

                    b.ToTable("INFORMACOESCOMPLEMENTARES");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.InformacoesComplementaresPessoaJuridica", b =>
                {
                    b.HasBaseType("DeslandesApp.Domain.Models.Entities.InformacoesComplementares");

                    b.Property<string>("Agencia")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("AGENCIA");

                    b.Property<string>("Cargo")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CARGO");

                    b.Property<string>("Contato")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CONTATO");

                    b.Property<string>("NomeBanco")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEBANCO");

                    b.Property<string>("NumeroConta")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NUMEROCONTA");

                    b.Property<string>("Pix")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PIX");

                    b.Property<int?>("TipoConta")
                        .HasColumnType("int")
                        .HasColumnName("TIPOCONTA");

                    b.ToTable("INFORMACOESCOMPLEMENTARES");

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaFisica", b =>
                {
                    b.HasBaseType("DeslandesApp.Domain.Models.Entities.Pessoa");

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CNH");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CPF");

                    b.Property<string>("CarteiraTrabalho")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CARTEIRATRABALHO");

                    b.Property<string>("CertidaoReservista")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CERTIDAORESERVISTA");

                    b.Property<string>("Passaporte")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("PASSAPORTE");

                    b.Property<string>("PisPasep")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("PISPASEP");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("RG");

                    b.Property<string>("TituloEleitor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("TITULOELEITOR");

                    b.ToTable("PESSOA");

                    b.HasDiscriminator().HasValue("PESSOAFISICA");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaJuridica", b =>
                {
                    b.HasBaseType("DeslandesApp.Domain.Models.Entities.Pessoa");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("INSCRICAOESTADUAL");

                    b.Property<string>("InscricaoMunicipal")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("INSCRICAOMUNICIPAL");

                    b.Property<int?>("SimplesNacional")
                        .HasColumnType("int")
                        .HasColumnName("SIMPLESNACIONAL");

                    b.ToTable("PESSOA");

                    b.HasDiscriminator().HasValue("PESSOAJURIDICA");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Endereco", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithOne("Endereco")
                        .HasForeignKey("DeslandesApp.Domain.Models.Entities.Endereco", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ENDERECO_PESSOA_PESSOA_ID");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.FailedLoginAttempt", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_FAILEDLOGINATTEMPTS_USUARIOS_IDUSUARIO");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Fotos", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithOne("Fotos")
                        .HasForeignKey("DeslandesApp.Domain.Models.Entities.Fotos", "IdUsuario")
                        .HasConstraintName("FK_FOTOS_USUARIOS_USUARIO_ID");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoEnvolvidos", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithMany("GrupoEnvolvidos")
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOENVOLVIDOS_PESSOA_IDPESSOA");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Processo", "Processo")
                        .WithMany("GrupoEnvolvidos")
                        .HasForeignKey("IdProcesso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOENVOLVIDOS_PROCESSO_IDPROCESSO");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Qualificacao", "QualificacaoEnvolvidos")
                        .WithMany()
                        .HasForeignKey("IdQualificacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOENVOLVIDOS_QUALIFICACAO_IDQUALIFICACAO");

                    b.Navigation("Pessoa");

                    b.Navigation("Processo");

                    b.Navigation("QualificacaoEnvolvidos");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoNiveis", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Niveis", "Niveis")
                        .WithMany("GrupoNiveis")
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPONIVEL_NIVEL_IDNIVEL");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany("GrupoNiveis")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPONIVEL_USUARIOS_IDUSUARIO");

                    b.Navigation("Niveis");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoPessoaClientes", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithMany("GrupoPessoaClientes")
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOPESSOACLIENTES_PESSOA_IDPESSOA");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Processo", "Processo")
                        .WithMany("GrupoPessoaClientes")
                        .HasForeignKey("IdProcesso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOPESSOACLIENTES_PROCESSO_IDPROCESSO");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Qualificacao", "QualificacaoCliente")
                        .WithMany()
                        .HasForeignKey("IdQualificacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOPESSOACLIENTES_QUALIFICACAO_IDQUALIFICACAO");

                    b.Navigation("Pessoa");

                    b.Navigation("Processo");

                    b.Navigation("QualificacaoCliente");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoSetores", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Setor", "Setor")
                        .WithMany("GrupoSetores")
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOSETORES_SETORES_IDSETOR");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany("GrupoSetores")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOSETORES_USUARIOS_IDUSUARIO");

                    b.Navigation("Setor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.InformacoesComplementares", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithOne("InformacoesComplementares")
                        .HasForeignKey("DeslandesApp.Domain.Models.Entities.InformacoesComplementares", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_INFORMACOESCOMPLEMENTARES_PESSOA_PESSOA_ID");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.LoginHistory", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LOGINHISTORY_USUARIOS_IDUSUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Pessoa", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Sexo", "Sexo")
                        .WithMany("Pessoa")
                        .HasForeignKey("IdSexo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PESSOA_SEXO_SEXO_ID");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany("Pessoa")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PESSOA_USUARIOS_USUARIO_ID");

                    b.Navigation("Sexo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaHistorico", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PESSOAHISTORICO_PESSOA");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PESSOAHISTORICO_USUARIO");

                    b.Navigation("Pessoa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Processo", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Acao", "Acao")
                        .WithMany()
                        .HasForeignKey("IdAcao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PROCESSO_ACAO_IDACAO");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Foro", "Foro")
                        .WithMany()
                        .HasForeignKey("IdForo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PROCESSO_FORO_IDFORO");

                    b.Navigation("Acao");

                    b.Navigation("Foro");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Niveis", b =>
                {
                    b.Navigation("GrupoNiveis");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Pessoa", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("GrupoEnvolvidos");

                    b.Navigation("GrupoPessoaClientes");

                    b.Navigation("InformacoesComplementares");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Processo", b =>
                {
                    b.Navigation("GrupoEnvolvidos");

                    b.Navigation("GrupoPessoaClientes");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Setor", b =>
                {
                    b.Navigation("GrupoSetores");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Sexo", b =>
                {
                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("GrupoNiveis");

                    b.Navigation("GrupoSetores");

                    b.Navigation("Pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
