// <auto-generated />
using System;
using DeslandesApp.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeslandesApp.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260306182816_EstruturaInicialCorrecao")]
    partial class EstruturaInicialCorrecao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CEP");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOA_ID");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("LOCALIDADE");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("LOGRADOURO");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NUMERO");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("UF");

                    b.HasKey("Id");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("ENDERECO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Fotos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("FotoNome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("FOTONOME");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasFilter("[USUARIO_ID] IS NOT NULL");

                    b.ToTable("FOTOS", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoNiveis", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNivel")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuario", "IdNivel");

                    b.HasIndex("IdNivel");

                    b.ToTable("GRUPONIVEL", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoSetores", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSetor")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuario", "IdSetor");

                    b.HasIndex("IdSetor");

                    b.ToTable("GRUPOSETORES", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.InformacoesComplementares", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AtividadeEconomica")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("ATIVIDADEECONOMICA");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("COMENTARIO");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("DATANASCIMENTO");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("ESTADOCIVIL");

                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOA_ID");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NASCIONALIDADE");

                    b.Property<string>("Naturalidade")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NATURALIDADE");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEEMPRESA");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEMAE");

                    b.Property<string>("NomePai")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEPAI");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("PROFISSAO");

                    b.HasKey("Id");

                    b.ToTable("INFORMACOESCOMPLEMENTARES", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Niveis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeNivel")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMENIVEL");

                    b.HasKey("Id");

                    b.ToTable("NIVEL", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATATATUALIZACAO");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<int?>("Etiqueta")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdEtiqueta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPessoa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSexo")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SEXO_ID");

                    b.Property<Guid?>("IdUsuarioCadastro")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOME");

                    b.Property<int?>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("TIPO")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("TipoEmail")
                        .HasColumnType("int");

                    b.Property<int?>("TipoTelefone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPessoa")
                        .IsUnique()
                        .HasFilter("[IdPessoa] IS NOT NULL");

                    b.HasIndex("IdSexo");

                    b.ToTable("PESSOA", (string)null);

                    b.HasDiscriminator<string>("TIPO").HasValue("Pessoa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeSetor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMESETOR");

                    b.HasKey("Id");

                    b.ToTable("SETORES", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Sexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeSexo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMESEXO");

                    b.HasKey("Id");

                    b.HasIndex("NomeSexo")
                        .IsUnique();

                    b.ToTable("SEXO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOA_ID");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("SENHA");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaFisica", b =>
                {
                    b.HasBaseType("DeslandesApp.Domain.Models.Entities.Pessoa");

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("CarteiraTrabalho")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("CertidaoReservista")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Passaporte")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PisPasep")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("TituloEleitor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasIndex("PessoaId");

                    b.ToTable("PESSOA");

                    b.HasDiscriminator().HasValue("PESSOAFISICA");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaJuridica", b =>
                {
                    b.HasBaseType("DeslandesApp.Domain.Models.Entities.Pessoa");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("InscricaoMunicipal")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SimplesNacional")
                        .HasColumnType("int");

                    b.HasIndex("PessoaId");

                    b.ToTable("PESSOA", t =>
                        {
                            t.Property("PessoaId")
                                .HasColumnName("PessoaJuridica_PessoaId");
                        });

                    b.HasDiscriminator().HasValue("PESSOAJURIDICA");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Endereco", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithOne("Endereco")
                        .HasForeignKey("DeslandesApp.Domain.Models.Entities.Endereco", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Fotos", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithOne("Fotos")
                        .HasForeignKey("DeslandesApp.Domain.Models.Entities.Fotos", "IdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoNiveis", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Niveis", "Niveis")
                        .WithMany("GrupoNiveis")
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany("GrupoNiveis")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Niveis");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoSetores", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Setor", "Setor")
                        .WithMany("GrupoSetores")
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany("GrupoSetores")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Pessoa", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.InformacoesComplementares", "InformacoesComplementares")
                        .WithOne("Pessoa")
                        .HasForeignKey("DeslandesApp.Domain.Models.Entities.Pessoa", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Sexo", "Sexo")
                        .WithMany("Pessoa")
                        .HasForeignKey("IdSexo");

                    b.OwnsOne("DeslandesApp.Domain.ValueObjects.ValorEmail", "ValorEmail", b1 =>
                        {
                            b1.Property<Guid>("PessoaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("EnderecoEmail")
                                .IsRequired()
                                .HasMaxLength(250)
                                .IsUnicode(false)
                                .HasColumnType("varchar(250)")
                                .HasColumnName("ValorEmail");

                            b1.HasKey("PessoaId");

                            b1.HasIndex("EnderecoEmail")
                                .IsUnique()
                                .HasFilter("[ValorEmail] IS NOT NULL");

                            b1.ToTable("PESSOA");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });

                    b.Navigation("InformacoesComplementares");

                    b.Navigation("Sexo");

                    b.Navigation("ValorEmail");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Usuario", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithOne("Usuario")
                        .HasForeignKey("DeslandesApp.Domain.Models.Entities.Usuario", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DeslandesApp.Domain.ValueObjects.ValorEmail", "ValorEmail", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("EnderecoEmail")
                                .IsRequired()
                                .HasMaxLength(250)
                                .IsUnicode(false)
                                .HasColumnType("varchar(250)")
                                .HasColumnName("ValorEmail");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("EnderecoEmail")
                                .IsUnique()
                                .HasFilter("[ValorEmail] IS NOT NULL");

                            b1.ToTable("USUARIOS");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Pessoa");

                    b.Navigation("ValorEmail");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaFisica", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaJuridica", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.InformacoesComplementares", b =>
                {
                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Niveis", b =>
                {
                    b.Navigation("GrupoNiveis");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Pessoa", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Setor", b =>
                {
                    b.Navigation("GrupoSetores");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Sexo", b =>
                {
                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("GrupoNiveis");

                    b.Navigation("GrupoSetores");
                });
#pragma warning restore 612, 618
        }
    }
}
