// <auto-generated />
using System;
using DeslandesApp.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeslandesApp.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260327161616_ProcessoHUpdate")]
    partial class ProcessoHUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Acao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("NomeAcao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NOMEACAO");

                    b.HasKey("Id")
                        .HasName("PK_ACAO");

                    b.ToTable("ACAO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Atendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ASSUNTO");

                    b.Property<Guid?>("AtendimentoPaiId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ATENDIMENTOPAIID");

                    b.Property<Guid?>("CasoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CASOID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<Guid?>("ProcessoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PROCESSOID");

                    b.Property<string>("Registro")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("REGISTRO");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RESPONSAVELID");

                    b.Property<int?>("TipoVinculo")
                        .HasColumnType("int")
                        .HasColumnName("TIPOVINCULO");

                    b.HasKey("Id")
                        .HasName("PK_ATENDIMENTO");

                    b.HasIndex("AtendimentoPaiId")
                        .HasDatabaseName("IX_ATENDIMENTO_ATENDIMENTOPAIID");

                    b.HasIndex("CasoId")
                        .HasDatabaseName("IX_ATENDIMENTO_CASOID");

                    b.HasIndex("ProcessoId")
                        .HasDatabaseName("IX_ATENDIMENTO_PROCESSOID");

                    b.HasIndex("ResponsavelId")
                        .HasDatabaseName("IX_ATENDIMENTO_RESPONSAVELID");

                    b.ToTable("ATENDIMENTO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Caso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<int>("Acesso")
                        .HasColumnType("int")
                        .HasColumnName("ACESSO");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<string>("Pasta")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("PASTA");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RESPONSAVELID");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id")
                        .HasName("PK_CASO");

                    b.HasIndex("ResponsavelId")
                        .HasDatabaseName("IX_CASO_RESPONSAVELID");

                    b.ToTable("CASO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Bairro")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("Cep")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CEP");

                    b.Property<string>("Complemento")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOA_ID");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("LOCALIDADE");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("LOGRADOURO");

                    b.Property<string>("Numero")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NUMERO");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("UF");

                    b.HasKey("Id")
                        .HasName("PK_ENDERECO");

                    b.HasIndex("IdPessoa")
                        .IsUnique()
                        .HasDatabaseName("IX_ENDERECO_PESSOA_ID");

                    b.ToTable("ENDERECO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Etiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOME");

                    b.HasKey("Id")
                        .HasName("PK_ETIQUETA");

                    b.ToTable("ETIQUETA");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<DateOnly?>("DataFimRecorrencia")
                        .HasColumnType("date")
                        .HasColumnName("DATAFIMRECORRENCIA");

                    b.Property<DateOnly?>("DataFinal")
                        .HasColumnType("date")
                        .HasColumnName("DATAFINAL");

                    b.Property<DateOnly>("DataInicial")
                        .HasColumnType("date")
                        .HasColumnName("DATAINICIAL");

                    b.Property<bool>("DiaInteiro")
                        .HasColumnType("bit")
                        .HasColumnName("DIAINTEIRO");

                    b.Property<string>("DiasSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIASSEMANA");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("ENDERECO");

                    b.Property<TimeOnly?>("HoraFinal")
                        .HasColumnType("time")
                        .HasColumnName("HORAFINAL");

                    b.Property<TimeOnly>("HoraInicial")
                        .HasColumnType("time")
                        .HasColumnName("HORAINICIAL");

                    b.Property<int>("IntervaloRecorrencia")
                        .HasColumnType("int")
                        .HasColumnName("INTERVALORECORRENCIA");

                    b.Property<int>("Modalidade")
                        .HasColumnType("int")
                        .HasColumnName("MODALIDADE");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<int?>("QuantidadeOcorrencias")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADEOCORRENCIAS");

                    b.Property<int>("StatusGeralKanban")
                        .HasColumnType("int")
                        .HasColumnName("STATUSKANBAN");

                    b.Property<int>("TipoRecorrencia")
                        .HasColumnType("int")
                        .HasColumnName("TIPORECORRENCIA");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("TITULO");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIOCRIACAOID");

                    b.HasKey("Id")
                        .HasName("PK_EVENTO");

                    b.HasIndex("UsuarioCriacaoId")
                        .HasDatabaseName("IX_EVENTO_USUARIOCRIACAOID");

                    b.ToTable("EVENTO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.FailedLoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDFAILEDLOGINATTEMPT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAHORA");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDUSUARIO");

                    b.Property<string>("IpAcesso")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IPACESSO");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("MENSAGEM");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("USERAGENT");

                    b.HasKey("Id")
                        .HasName("PK_FAILEDLOGINATTEMPTS");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_FAILEDLOGINATTEMPTS_IDUSUARIO");

                    b.ToTable("FAILEDLOGINATTEMPTS", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Foro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("NomeForo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NOMEFORO");

                    b.HasKey("Id")
                        .HasName("PK_FORO");

                    b.HasIndex("NomeForo")
                        .IsUnique()
                        .HasDatabaseName("IX_FORO_NOMEFORO");

                    b.ToTable("FORO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Fotos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("FILEURL");

                    b.Property<string>("FotoNome")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("FOTONOME");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id")
                        .HasName("PK_FOTOS");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("IX_FOTOS_USUARIO_ID")
                        .HasFilter("[USUARIO_ID] IS NOT NULL");

                    b.ToTable("FOTOS", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoAtendimentoCliente", b =>
                {
                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ATENDIMENTOID");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOAID");

                    b.HasKey("AtendimentoId", "PessoaId")
                        .HasName("PK_GRUPOATENDIMENTOCLIENTE");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("IX_GRUPOATENDIMENTOCLIENTE_PESSOAID");

                    b.ToTable("GRUPOATENDIMENTOCLIENTE", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoAtendimentoEtiqueta", b =>
                {
                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ATENDIMENTOID");

                    b.Property<Guid>("EtiquetaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ETIQUETAID");

                    b.HasKey("AtendimentoId", "EtiquetaId")
                        .HasName("PK_GRUPOATENDIMENTOETIQUETA");

                    b.HasIndex("EtiquetaId")
                        .HasDatabaseName("IX_GRUPOATENDIMENTOETIQUETA_ETIQUETAID");

                    b.ToTable("GRUPOATENDIMENTOETIQUETA", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoCasoCliente", b =>
                {
                    b.Property<Guid>("CasoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CASOID");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOAID");

                    b.Property<Guid?>("QualificacaoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QUALIFICACAOID");

                    b.HasKey("CasoId", "PessoaId")
                        .HasName("PK_GRUPOCASOCLIENTE");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("IX_GRUPOCASOCLIENTE_PESSOAID");

                    b.HasIndex("QualificacaoId")
                        .HasDatabaseName("IX_GRUPOCASOCLIENTE_QUALIFICACAOID");

                    b.ToTable("GRUPOCASOCLIENTE", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoCasoEnvolvido", b =>
                {
                    b.Property<Guid>("CasoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CASOID");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOAID");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<Guid?>("QualificacaoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QUALIFICACAOID");

                    b.HasKey("CasoId", "PessoaId")
                        .HasName("PK_GRUPOCASOENVOLVIDO");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("IX_GRUPOCASOENVOLVIDO_PESSOAID");

                    b.HasIndex("QualificacaoId")
                        .HasDatabaseName("IX_GRUPOCASOENVOLVIDO_QUALIFICACAOID");

                    b.ToTable("GRUPOCASOENVOLVIDO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoEnvolvidos", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOAID");

                    b.Property<Guid>("ProcessoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PROCESSOID");

                    b.Property<Guid>("QualificacaoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QUALIFICACAOID");

                    b.HasKey("PessoaId", "ProcessoId", "QualificacaoId")
                        .HasName("PK_GRUPOENVOLVIDOS");

                    b.HasIndex("ProcessoId")
                        .HasDatabaseName("IX_GRUPOENVOLVIDOS_PROCESSOID");

                    b.HasIndex("QualificacaoId")
                        .HasDatabaseName("IX_GRUPOENVOLVIDOS_QUALIFICACAOID");

                    b.ToTable("GRUPOENVOLVIDOS");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoEventoResponsavel", b =>
                {
                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EVENTOID");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIOID");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.HasKey("EventoId", "UsuarioId")
                        .HasName("PK_EVENTORESPONSAVEL");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_EVENTORESPONSAVEL_USUARIOID");

                    b.ToTable("EVENTORESPONSAVEL", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoNiveis", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDUSUARIO");

                    b.Property<Guid>("IdNivel")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDNIVEL");

                    b.HasKey("IdUsuario", "IdNivel")
                        .HasName("PK_GRUPONIVEL");

                    b.HasIndex("IdNivel")
                        .HasDatabaseName("IX_GRUPONIVEL_IDNIVEL");

                    b.ToTable("GRUPONIVEL", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoPessoaClientes", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOAID");

                    b.Property<Guid>("ProcessoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PROCESSOID");

                    b.Property<Guid>("QualificacaoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QUALIFICACAOID");

                    b.HasKey("PessoaId", "ProcessoId", "QualificacaoId")
                        .HasName("PK_GRUPOPESSOACLIENTES");

                    b.HasIndex("ProcessoId")
                        .HasDatabaseName("IX_GRUPOPESSOACLIENTES_PROCESSOID");

                    b.HasIndex("QualificacaoId")
                        .HasDatabaseName("IX_GRUPOPESSOACLIENTES_QUALIFICACAOID");

                    b.ToTable("GRUPOPESSOACLIENTES");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoSetores", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDUSUARIO");

                    b.Property<Guid>("IdSetor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDSETOR");

                    b.HasKey("IdUsuario", "IdSetor")
                        .HasName("PK_GRUPOSETORES");

                    b.HasIndex("IdSetor")
                        .HasDatabaseName("IX_GRUPOSETORES_IDSETOR");

                    b.ToTable("GRUPOSETORES", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoTarefaEnvolvido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOAID");

                    b.Property<Guid>("TarefaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TAREFAID");

                    b.HasKey("Id")
                        .HasName("PK_GRUPOTAREFAENVOLVIDO");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("IX_GRUPOTAREFAENVOLVIDO_PESSOAID");

                    b.HasIndex("TarefaId", "PessoaId")
                        .IsUnique()
                        .HasDatabaseName("IX_GRUPOTAREFAENVOLVIDO_TAREFAID_PESSOAID");

                    b.ToTable("GRUPOTAREFAENVOLVIDO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.InformacoesComplementares", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Comentario")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("COMENTARIO");

                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOA_ID");

                    b.Property<string>("TIPOPESSOA")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("TIPOPESSOA");

                    b.HasKey("Id")
                        .HasName("PK_INFORMACOESCOMPLEMENTARES");

                    b.HasIndex("IdPessoa")
                        .IsUnique()
                        .HasDatabaseName("IX_INFORMACOESCOMPLEMENTARES_PESSOA_ID");

                    b.ToTable("INFORMACOESCOMPLEMENTARES", (string)null);

                    b.HasDiscriminator<string>("TIPOPESSOA").HasValue("InformacoesComplementares");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.ListaTarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<bool?>("Concluida")
                        .HasColumnType("bit")
                        .HasColumnName("CONCLUIDA");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACONCLUSAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("ORDEM");

                    b.Property<Guid?>("TarefaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TAREFAID");

                    b.HasKey("Id")
                        .HasName("PK_LISTATAREFA");

                    b.HasIndex("TarefaId")
                        .HasDatabaseName("IX_LISTATAREFA_TAREFAID");

                    b.ToTable("LISTATAREFA", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.LoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataHoraAcesso")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAHORAACESSO");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDUSUARIO");

                    b.Property<string>("IpAcesso")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("IPACESSO");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("MENSAGEM");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("bit")
                        .HasColumnName("SUCESSO");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("USERAGENT");

                    b.HasKey("Id")
                        .HasName("PK_LOGINHISTORY");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_LOGINHISTORY_IDUSUARIO");

                    b.ToTable("LOGINHISTORY", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Niveis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("NomeNivel")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMENIVEL");

                    b.HasKey("Id")
                        .HasName("PK_NIVEL");

                    b.ToTable("NIVEL", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Apelido")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("APELIDO");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<Guid?>("EtiquetaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ETIQUETAID");

                    b.Property<Guid?>("IdSexo")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SEXO_ID");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOME");

                    b.Property<int?>("Perfil")
                        .HasColumnType("int")
                        .HasColumnName("PERFIL");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("SITE");

                    b.Property<string>("TIPO")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("TIPO");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("TELEFONE");

                    b.Property<int?>("TipoEmail")
                        .HasColumnType("int")
                        .HasColumnName("TIPOEMAIL");

                    b.Property<string>("ValorEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAIL");

                    b.HasKey("Id")
                        .HasName("PK_PESSOA");

                    b.HasIndex("EtiquetaId")
                        .HasDatabaseName("IX_PESSOA_ETIQUETAID");

                    b.HasIndex("IdSexo")
                        .HasDatabaseName("IX_PESSOA_SEXO_ID");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_PESSOA_USUARIO_ID");

                    b.ToTable("PESSOA", (string)null);

                    b.HasDiscriminator<string>("TIPO").HasValue("Pessoa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("DadosAntes")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("DADOSANTES");

                    b.Property<string>("DadosDepois")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("DADOSDEPOIS");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAALTERACAO");

                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PESSOA_ID");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("OBSERVACOES");

                    b.HasKey("Id")
                        .HasName("PK_PESSOAHISTORICO");

                    b.HasIndex("IdPessoa")
                        .HasDatabaseName("IX_PESSOAHISTORICO_PESSOA_ID");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_PESSOAHISTORICO_USUARIO_ID");

                    b.ToTable("PESSOAHISTORICO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.ProcessoHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("DadosAntes")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("DADOSANTES");

                    b.Property<string>("DadosDepois")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("DADOSDEPOIS");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAALTERACAO");

                    b.Property<Guid?>("IdAcao")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDACAO");

                    b.Property<Guid>("IdProcesso")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDPROCESSO");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("OBSERVACOES");

                    b.HasKey("Id")
                        .HasName("PK_PROCESSOHISTORICO");

                    b.HasIndex("IdAcao")
                        .HasDatabaseName("IX_PROCESSOHISTORICO_IDACAO");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_PROCESSOHISTORICO_USUARIO_ID");

                    b.ToTable("PROCESSOHISTORICO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Qualificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("NomeQualificacao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NOMEQUALIFICACAO");

                    b.HasKey("Id")
                        .HasName("PK_QUALIFICACAO");

                    b.ToTable("QUALIFICACAO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("NomeSetor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NOMESETOR");

                    b.HasKey("Id")
                        .HasName("PK_SETORES");

                    b.ToTable("SETORES", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Sexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("NomeSexo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOMESEXO");

                    b.HasKey("Id")
                        .HasName("PK_SEXO");

                    b.HasIndex("NomeSexo")
                        .IsUnique()
                        .HasDatabaseName("IX_SEXO_NOMESEXO");

                    b.ToTable("SEXO", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Tarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<Guid?>("AtendimentoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ATENDIMENTOID");

                    b.Property<Guid?>("CasoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CASOID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<DateTime?>("DataTarefa")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATATAREFA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasColumnName("PRIORIDADE");

                    b.Property<Guid?>("ProcessoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PROCESSOID");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RESPONSAVELID");

                    b.Property<int>("StatusGeralKanban")
                        .HasColumnType("int")
                        .HasColumnName("STATUSKANBAN");

                    b.Property<int?>("TipoVinculo")
                        .HasColumnType("int")
                        .HasColumnName("TIPOVINCULO");

                    b.Property<Guid?>("UsuarioCriacaoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIOCRIACAOID");

                    b.HasKey("Id")
                        .HasName("PK_TAREFA");

                    b.HasIndex("AtendimentoId")
                        .HasDatabaseName("IX_TAREFA_ATENDIMENTOID");

                    b.HasIndex("CasoId")
                        .HasDatabaseName("IX_TAREFA_CASOID");

                    b.HasIndex("ProcessoId")
                        .HasDatabaseName("IX_TAREFA_PROCESSOID");

                    b.HasIndex("ResponsavelId")
                        .HasDatabaseName("IX_TAREFA_RESPONSAVELID");

                    b.HasIndex("UsuarioCriacaoId")
                        .HasDatabaseName("IX_TAREFA_USUARIOCRIACAOID");

                    b.ToTable("TAREFA", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.TarefaEtiqueta", b =>
                {
                    b.Property<Guid>("TarefaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TAREFAID");

                    b.Property<Guid>("EtiquetaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ETIQUETAID");

                    b.HasKey("TarefaId", "EtiquetaId")
                        .HasName("PK_TAREFAETIQUETA");

                    b.HasIndex("EtiquetaId")
                        .HasDatabaseName("IX_TAREFAETIQUETA_ETIQUETAID");

                    b.ToTable("TAREFAETIQUETA", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAATUALIZACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("NomeUsuario")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEUSUARIO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("SENHA");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("ValorEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAIL");

                    b.HasKey("Id")
                        .HasName("PK_USUARIOS");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Vara", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<Guid>("ForoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FOROID");

                    b.Property<string>("NomeVara")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NOMEVARA");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id")
                        .HasName("PK_VARA");

                    b.HasIndex("ForoId")
                        .HasDatabaseName("IX_VARA_FOROID");

                    b.HasIndex("Numero", "Tipo", "ForoId")
                        .IsUnique()
                        .HasDatabaseName("IX_VARA_NUMERO_TIPO_FOROID");

                    b.ToTable("VARA", (string)null);
                });

            modelBuilder.Entity("Processo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<Guid?>("AcaoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ACAOID");

                    b.Property<int?>("Acesso")
                        .HasColumnType("int")
                        .HasColumnName("ACESSO");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATACADASTRO");

                    b.Property<DateTime?>("Distribuido")
                        .HasColumnType("datetime2")
                        .HasColumnName("DISTRIBUIDO");

                    b.Property<int?>("Etiqueta")
                        .HasColumnType("int")
                        .HasColumnName("ETIQUETA");

                    b.Property<int?>("Instancia")
                        .HasColumnType("int")
                        .HasColumnName("INSTANCIA");

                    b.Property<string>("LinkTribunal")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("LINKTRIBUNAL");

                    b.Property<string>("NumeroProcesso")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NUMEROPROCESSO");

                    b.Property<string>("Objeto")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("OBJETO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<string>("Pasta")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("PASTA");

                    b.Property<string>("Titulo")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("TITULO");

                    b.Property<Guid?>("UsuarioResponsavelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIORESPONSAVELID");

                    b.Property<decimal?>("ValorCausa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALORCAUSA");

                    b.Property<decimal?>("ValorCondenacao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALORCONDENACAO");

                    b.Property<Guid>("VaraId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VARAID");

                    b.HasKey("Id")
                        .HasName("PK_PROCESSOS");

                    b.HasIndex("AcaoId")
                        .HasDatabaseName("IX_PROCESSOS_ACAOID");

                    b.HasIndex("UsuarioResponsavelId")
                        .HasDatabaseName("IX_PROCESSOS_USUARIORESPONSAVELID");

                    b.HasIndex("VaraId")
                        .HasDatabaseName("IX_PROCESSOS_VARAID");

                    b.ToTable("PROCESSOS");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.InformacoesComplementaresPessoaFisica", b =>
                {
                    b.HasBaseType("DeslandesApp.Domain.Models.Entities.InformacoesComplementares");

                    b.Property<string>("AtividadeEconomica")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ATIVIDADEECONOMICA");

                    b.Property<string>("DataNascimento")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("DATANASCIMENTO");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ESTADOCIVIL");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NACIONALIDADE");

                    b.Property<string>("Naturalidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NATURALIDADE");

                    b.Property<string>("NomeEmpresa")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEEMPRESA");

                    b.Property<string>("NomeMae")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEMAE");

                    b.Property<string>("NomePai")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEPAI");

                    b.Property<string>("Profissao")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("PROFISSAO");

                    b.ToTable("INFORMACOESCOMPLEMENTARES");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.InformacoesComplementaresPessoaJuridica", b =>
                {
                    b.HasBaseType("DeslandesApp.Domain.Models.Entities.InformacoesComplementares");

                    b.Property<string>("Agencia")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("AGENCIA");

                    b.Property<string>("Cargo")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CARGO");

                    b.Property<string>("Contato")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CONTATO");

                    b.Property<string>("NomeBanco")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMEBANCO");

                    b.Property<string>("NumeroConta")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NUMEROCONTA");

                    b.Property<string>("Pix")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PIX");

                    b.Property<int?>("TipoConta")
                        .HasColumnType("int")
                        .HasColumnName("TIPOCONTA");

                    b.ToTable("INFORMACOESCOMPLEMENTARES");

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaFisica", b =>
                {
                    b.HasBaseType("DeslandesApp.Domain.Models.Entities.Pessoa");

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CNH");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CPF");

                    b.Property<string>("CarteiraTrabalho")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CARTEIRATRABALHO");

                    b.Property<string>("CertidaoReservista")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CERTIDAORESERVISTA");

                    b.Property<string>("Passaporte")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("PASSAPORTE");

                    b.Property<string>("PisPasep")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("PISPASEP");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("RG");

                    b.Property<string>("TituloEleitor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("TITULOELEITOR");

                    b.ToTable("PESSOA");

                    b.HasDiscriminator().HasValue("PESSOAFISICA");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaJuridica", b =>
                {
                    b.HasBaseType("DeslandesApp.Domain.Models.Entities.Pessoa");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("INSCRICAOESTADUAL");

                    b.Property<string>("InscricaoMunicipal")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("INSCRICAOMUNICIPAL");

                    b.Property<int?>("SimplesNacional")
                        .HasColumnType("int")
                        .HasColumnName("SIMPLESNACIONAL");

                    b.ToTable("PESSOA");

                    b.HasDiscriminator().HasValue("PESSOAJURIDICA");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Atendimento", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Atendimento", "AtendimentoPai")
                        .WithMany()
                        .HasForeignKey("AtendimentoPaiId")
                        .HasConstraintName("FK_ATENDIMENTO_ATENDIMENTO_ATENDIMENTOPAIID");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Caso", "Caso")
                        .WithMany()
                        .HasForeignKey("CasoId")
                        .HasConstraintName("FK_ATENDIMENTO_CASO_CASOID");

                    b.HasOne("Processo", "Processo")
                        .WithMany()
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ATENDIMENTO_PROCESSO");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .HasConstraintName("FK_ATENDIMENTO_USUARIOS_RESPONSAVELID");

                    b.Navigation("AtendimentoPai");

                    b.Navigation("Caso");

                    b.Navigation("Processo");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Caso", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CASO_USUARIO");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Endereco", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithOne("Endereco")
                        .HasForeignKey("DeslandesApp.Domain.Models.Entities.Endereco", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ENDERECO_PESSOA_PESSOA_ID");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Evento", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_EVENTO_USUARIOS_USUARIOCRIACAOID");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.FailedLoginAttempt", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_FAILEDLOGINATTEMPTS_USUARIOS_IDUSUARIO");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Fotos", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithOne("Fotos")
                        .HasForeignKey("DeslandesApp.Domain.Models.Entities.Fotos", "IdUsuario")
                        .HasConstraintName("FK_FOTOS_USUARIOS_USUARIO_ID");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoAtendimentoCliente", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Atendimento", "Atendimento")
                        .WithMany("GrupoClientes")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ATENDIMENTO_ATENDIMENTCLIENTE");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOATENDIMENTOCLIENTE_PESSOA_PESSOAID");

                    b.Navigation("Atendimento");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoAtendimentoEtiqueta", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Atendimento", "Atendimento")
                        .WithMany("GrupoEtiquetas")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ATENDIMENTO_ETIQUETA");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Etiqueta", "Etiqueta")
                        .WithMany()
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOATENDIMENTOETIQUETA_ETIQUETA_ETIQUETAID");

                    b.Navigation("Atendimento");

                    b.Navigation("Etiqueta");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoCasoCliente", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Caso", "Caso")
                        .WithMany("GrupoCasoCliente")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CASO_CASOCLIENTE");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOCASOCLIENTE_PESSOA_PESSOAID");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Qualificacao", "QualificacaoCliente")
                        .WithMany()
                        .HasForeignKey("QualificacaoId")
                        .HasConstraintName("FK_GRUPOCASOCLIENTE_QUALIFICACAO_QUALIFICACAOID");

                    b.Navigation("Caso");

                    b.Navigation("Pessoa");

                    b.Navigation("QualificacaoCliente");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoCasoEnvolvido", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Caso", "Caso")
                        .WithMany("GrupoCasoEnvolvido")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CASO_CASOENVOLVIDO");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOCASOENVOLVIDO_PESSOA_PESSOAID");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Qualificacao", "Qualificacao")
                        .WithMany()
                        .HasForeignKey("QualificacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_GRUPOCASOENVOLVIDO_QUALIFICACAO_QUALIFICACAOID");

                    b.Navigation("Caso");

                    b.Navigation("Pessoa");

                    b.Navigation("Qualificacao");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoEnvolvidos", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithMany("GrupoEnvolvidos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOENVOLVIDOS_PESSOA_PESSOAID");

                    b.HasOne("Processo", "Processo")
                        .WithMany("GrupoEnvolvidos")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOENVOLVIDOS_PROCESSOS_PROCESSOID");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Qualificacao", "QualificacaoEnvolvidos")
                        .WithMany()
                        .HasForeignKey("QualificacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOENVOLVIDOS_QUALIFICACAO_QUALIFICACAOID");

                    b.Navigation("Pessoa");

                    b.Navigation("Processo");

                    b.Navigation("QualificacaoEnvolvidos");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoEventoResponsavel", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Evento", "Evento")
                        .WithMany("GrupoEventoResponsavel")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EVENTO_EVENTORESPONSAVEL");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EVENTORESPONSAVEL_USUARIOS_USUARIOID");

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoNiveis", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Niveis", "Niveis")
                        .WithMany("GrupoNiveis")
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPONIVEL_NIVEL_IDNIVEL");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany("GrupoNiveis")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPONIVEL_USUARIOS_IDUSUARIO");

                    b.Navigation("Niveis");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoPessoaClientes", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithMany("GrupoPessoaClientes")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOPESSOACLIENTES_PESSOA_PESSOAID");

                    b.HasOne("Processo", "Processo")
                        .WithMany("GrupoPessoaClientes")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOPESSOACLIENTES_PROCESSOS_PROCESSOID");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Qualificacao", "QualificacaoCliente")
                        .WithMany()
                        .HasForeignKey("QualificacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOPESSOACLIENTES_QUALIFICACAO_QUALIFICACAOID");

                    b.Navigation("Pessoa");

                    b.Navigation("Processo");

                    b.Navigation("QualificacaoCliente");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoSetores", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Setor", "Setor")
                        .WithMany("GrupoSetores")
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOSETORES_SETORES_IDSETOR");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany("GrupoSetores")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GRUPOSETORES_USUARIOS_IDUSUARIO");

                    b.Navigation("Setor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.GrupoTarefaEnvolvido", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithMany("GrupoTarefaEnvolvido")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TAREFAENVOLVIDO_PESSOA");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Tarefa", "Tarefa")
                        .WithMany("GrupoTarefaEnvolvido")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TAREFA_ENVOLVIDO");

                    b.Navigation("Pessoa");

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.InformacoesComplementares", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithOne("InformacoesComplementares")
                        .HasForeignKey("DeslandesApp.Domain.Models.Entities.InformacoesComplementares", "IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_INFORMACOESCOMPLEMENTARES_PESSOA_PESSOA_ID");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.ListaTarefa", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Tarefa", "Tarefa")
                        .WithMany("ListasTarefa")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_TAREFA_LISTATAREFA");

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.LoginHistory", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LOGINHISTORY_USUARIOS_IDUSUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Pessoa", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Etiqueta", "Etiqueta")
                        .WithMany()
                        .HasForeignKey("EtiquetaId")
                        .HasConstraintName("FK_PESSOA_ETIQUETA_ETIQUETAID");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Sexo", "Sexo")
                        .WithMany("Pessoa")
                        .HasForeignKey("IdSexo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PESSOA_SEXO_SEXO_ID");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany("Pessoa")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PESSOA_USUARIOS_USUARIO_ID");

                    b.Navigation("Etiqueta");

                    b.Navigation("Sexo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.PessoaHistorico", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PESSOAHISTORICO_PESSOA");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PESSOAHISTORICO_USUARIO");

                    b.Navigation("Pessoa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.ProcessoHistorico", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Acao", "Acao")
                        .WithMany()
                        .HasForeignKey("IdAcao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PROCESSOHISTORICO_ACAO");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_USUARIOHISTORICO_USUARIO");

                    b.Navigation("Acao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Tarefa", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Atendimento", "Atendimento")
                        .WithMany()
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_TAREFA_ATENDIMENTO");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Caso", "Caso")
                        .WithMany()
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_TAREFA_CASO");

                    b.HasOne("Processo", "Processo")
                        .WithMany()
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_TAREFA_PROCESSO");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_TAREFA_USUARIO");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_TAREFA_USUARIOS_USUARIOCRIACAOID");

                    b.Navigation("Atendimento");

                    b.Navigation("Caso");

                    b.Navigation("Processo");

                    b.Navigation("Responsavel");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.TarefaEtiqueta", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Etiqueta", "Etiqueta")
                        .WithMany("TarefaEtiquetas")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TAREFAETIQUETA_ETIQUETA");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Tarefa", "Tarefa")
                        .WithMany("TarefaEtiquetas")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TAREFAETIQUETA_TAREFA");

                    b.Navigation("Etiqueta");

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Vara", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Foro", "Foro")
                        .WithMany("Varas")
                        .HasForeignKey("ForoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VARA_FORO_FOROID");

                    b.Navigation("Foro");
                });

            modelBuilder.Entity("Processo", b =>
                {
                    b.HasOne("DeslandesApp.Domain.Models.Entities.Acao", "Acao")
                        .WithMany()
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PROCESSOS_ACAO_ACAOID");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Usuario", "UsuarioResponsavel")
                        .WithMany("ProcessosResponsaveis")
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_PROCESSOS_USUARIOS_USUARIORESPONSAVELID");

                    b.HasOne("DeslandesApp.Domain.Models.Entities.Vara", "Vara")
                        .WithMany("Processos")
                        .HasForeignKey("VaraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PROCESSOS_VARA_VARAID");

                    b.Navigation("Acao");

                    b.Navigation("UsuarioResponsavel");

                    b.Navigation("Vara");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Atendimento", b =>
                {
                    b.Navigation("GrupoClientes");

                    b.Navigation("GrupoEtiquetas");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Caso", b =>
                {
                    b.Navigation("GrupoCasoCliente");

                    b.Navigation("GrupoCasoEnvolvido");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Etiqueta", b =>
                {
                    b.Navigation("TarefaEtiquetas");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Evento", b =>
                {
                    b.Navigation("GrupoEventoResponsavel");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Foro", b =>
                {
                    b.Navigation("Varas");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Niveis", b =>
                {
                    b.Navigation("GrupoNiveis");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Pessoa", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("GrupoEnvolvidos");

                    b.Navigation("GrupoPessoaClientes");

                    b.Navigation("GrupoTarefaEnvolvido");

                    b.Navigation("InformacoesComplementares");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Setor", b =>
                {
                    b.Navigation("GrupoSetores");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Sexo", b =>
                {
                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Tarefa", b =>
                {
                    b.Navigation("GrupoTarefaEnvolvido");

                    b.Navigation("ListasTarefa");

                    b.Navigation("TarefaEtiquetas");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("GrupoNiveis");

                    b.Navigation("GrupoSetores");

                    b.Navigation("Pessoa");

                    b.Navigation("ProcessosResponsaveis");
                });

            modelBuilder.Entity("DeslandesApp.Domain.Models.Entities.Vara", b =>
                {
                    b.Navigation("Processos");
                });

            modelBuilder.Entity("Processo", b =>
                {
                    b.Navigation("GrupoEnvolvidos");

                    b.Navigation("GrupoPessoaClientes");
                });
#pragma warning restore 612, 618
        }
    }
}
