//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.wsPublicacaoSoap")]
    public interface wsPublicacaoSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPublicacoesV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(estatisticasPublicacoesBase))]
        System.Threading.Tasks.Task<ServiceReference1.getPublicacoesVResponse> getPublicacoesVAsync(ServiceReference1.getPublicacoesVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPublicacoes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(estatisticasPublicacoesBase))]
        System.Threading.Tasks.Task<ServiceReference1.getPublicacoesResponse> getPublicacoesAsync(ServiceReference1.getPublicacoesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPublicacoesNaoExportadasV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(estatisticasPublicacoesBase))]
        System.Threading.Tasks.Task<ServiceReference1.getPublicacoesNaoExportadasVResponse> getPublicacoesNaoExportadasVAsync(ServiceReference1.getPublicacoesNaoExportadasVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPublicacoesNaoExportadas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(estatisticasPublicacoesBase))]
        System.Threading.Tasks.Task<ServiceReference1.getPublicacoesNaoExportadasResponse> getPublicacoesNaoExportadasAsync(ServiceReference1.getPublicacoesNaoExportadasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setPublicacoesGrupo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(estatisticasPublicacoesBase))]
        System.Threading.Tasks.Task<ServiceReference1.setPublicacoesGrupoResponse> setPublicacoesGrupoAsync(ServiceReference1.setPublicacoesGrupoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setPublicacoes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(estatisticasPublicacoesBase))]
        System.Threading.Tasks.Task<ServiceReference1.setPublicacoesResponse> setPublicacoesAsync(ServiceReference1.setPublicacoesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEstatisticasPublicacoes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(estatisticasPublicacoesBase))]
        System.Threading.Tasks.Task<ServiceReference1.getEstatisticasPublicacoesResponse> getEstatisticasPublicacoesAsync(ServiceReference1.getEstatisticasPublicacoesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/waitSeconds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(estatisticasPublicacoesBase))]
        System.Threading.Tasks.Task<ServiceReference1.waitSecondsResponse> waitSecondsAsync(ServiceReference1.waitSecondsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class listaPublicacao
    {
        
        private publicacao[] publicacaoField;
        
        private publicacao[] publicacaoV2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("publicacao", Order=0)]
        public publicacao[] publicacao
        {
            get
            {
                return this.publicacaoField;
            }
            set
            {
                this.publicacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("publicacaoV2", Order=1)]
        public publicacao[] publicacaoV2
        {
            get
            {
                return this.publicacaoV2Field;
            }
            set
            {
                this.publicacaoV2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(publicacaoV2))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(publicacaoV4))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(publicacaoV5))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class publicacao
    {
        
        private int anoPublicacaoField;
        
        private long codPublicacaoField;
        
        private int edicaoDiarioField;
        
        private string descricaoDiarioField;
        
        private int paginaInicialField;
        
        private int paginaFinalField;
        
        private string dataPublicacaoField;
        
        private string dataDivulgacaoField;
        
        private string dataCadastroField;
        
        private string numeroProcessoField;
        
        private string ufPublicacaoField;
        
        private string cidadePublicacaoField;
        
        private string orgaoDescricaoField;
        
        private string varaDescricaoField;
        
        private string despachoPublicacaoField;
        
        private string processoPublicacaoField;
        
        private int publicacaoCorrigidaField;
        
        private int codVinculoField;
        
        private string nomeVinculoField;
        
        private int oABNumeroField;
        
        private string oABEstadoField;
        
        private string codIntegracaoField;
        
        private int publicacaoExportadaField;
        
        private int codGrupoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int anoPublicacao
        {
            get
            {
                return this.anoPublicacaoField;
            }
            set
            {
                this.anoPublicacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long codPublicacao
        {
            get
            {
                return this.codPublicacaoField;
            }
            set
            {
                this.codPublicacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int edicaoDiario
        {
            get
            {
                return this.edicaoDiarioField;
            }
            set
            {
                this.edicaoDiarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string descricaoDiario
        {
            get
            {
                return this.descricaoDiarioField;
            }
            set
            {
                this.descricaoDiarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int paginaInicial
        {
            get
            {
                return this.paginaInicialField;
            }
            set
            {
                this.paginaInicialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int paginaFinal
        {
            get
            {
                return this.paginaFinalField;
            }
            set
            {
                this.paginaFinalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string dataPublicacao
        {
            get
            {
                return this.dataPublicacaoField;
            }
            set
            {
                this.dataPublicacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string dataDivulgacao
        {
            get
            {
                return this.dataDivulgacaoField;
            }
            set
            {
                this.dataDivulgacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string dataCadastro
        {
            get
            {
                return this.dataCadastroField;
            }
            set
            {
                this.dataCadastroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string numeroProcesso
        {
            get
            {
                return this.numeroProcessoField;
            }
            set
            {
                this.numeroProcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ufPublicacao
        {
            get
            {
                return this.ufPublicacaoField;
            }
            set
            {
                this.ufPublicacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string cidadePublicacao
        {
            get
            {
                return this.cidadePublicacaoField;
            }
            set
            {
                this.cidadePublicacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string orgaoDescricao
        {
            get
            {
                return this.orgaoDescricaoField;
            }
            set
            {
                this.orgaoDescricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string varaDescricao
        {
            get
            {
                return this.varaDescricaoField;
            }
            set
            {
                this.varaDescricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string despachoPublicacao
        {
            get
            {
                return this.despachoPublicacaoField;
            }
            set
            {
                this.despachoPublicacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string processoPublicacao
        {
            get
            {
                return this.processoPublicacaoField;
            }
            set
            {
                this.processoPublicacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int publicacaoCorrigida
        {
            get
            {
                return this.publicacaoCorrigidaField;
            }
            set
            {
                this.publicacaoCorrigidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int codVinculo
        {
            get
            {
                return this.codVinculoField;
            }
            set
            {
                this.codVinculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string nomeVinculo
        {
            get
            {
                return this.nomeVinculoField;
            }
            set
            {
                this.nomeVinculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int OABNumero
        {
            get
            {
                return this.oABNumeroField;
            }
            set
            {
                this.oABNumeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string OABEstado
        {
            get
            {
                return this.oABEstadoField;
            }
            set
            {
                this.oABEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string codIntegracao
        {
            get
            {
                return this.codIntegracaoField;
            }
            set
            {
                this.codIntegracaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int publicacaoExportada
        {
            get
            {
                return this.publicacaoExportadaField;
            }
            set
            {
                this.publicacaoExportadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int codGrupo
        {
            get
            {
                return this.codGrupoField;
            }
            set
            {
                this.codGrupoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(estatisticasPublicacoes))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class estatisticasPublicacoesBase
    {
        
        private string grupoField;
        
        private int totalPublicacoesField;
        
        private int totalNaoImportadasField;
        
        private estatisticasPublicacoes[] detalhamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string grupo
        {
            get
            {
                return this.grupoField;
            }
            set
            {
                this.grupoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int totalPublicacoes
        {
            get
            {
                return this.totalPublicacoesField;
            }
            set
            {
                this.totalPublicacoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int totalNaoImportadas
        {
            get
            {
                return this.totalNaoImportadasField;
            }
            set
            {
                this.totalNaoImportadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item")]
        public estatisticasPublicacoes[] detalhamento
        {
            get
            {
                return this.detalhamentoField;
            }
            set
            {
                this.detalhamentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class estatisticasPublicacoes : estatisticasPublicacoesBase
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(publicacaoV4))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(publicacaoV5))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class publicacaoV2 : publicacao
    {
        
        private string naturezaField;
        
        private string complemento1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string natureza
        {
            get
            {
                return this.naturezaField;
            }
            set
            {
                this.naturezaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string complemento1
        {
            get
            {
                return this.complemento1Field;
            }
            set
            {
                this.complemento1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(publicacaoV5))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class publicacaoV4 : publicacaoV2
    {
        
        private string orgaoDescricaoCompField;
        
        private string diarioSiglaWjField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string orgaoDescricaoComp
        {
            get
            {
                return this.orgaoDescricaoCompField;
            }
            set
            {
                this.orgaoDescricaoCompField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string diarioSiglaWj
        {
            get
            {
                return this.diarioSiglaWjField;
            }
            set
            {
                this.diarioSiglaWjField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class publicacaoV5 : publicacaoV4
    {
        
        private string anexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string anexo
        {
            get
            {
                return this.anexoField;
            }
            set
            {
                this.anexoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPublicacoesV", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getPublicacoesVRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strSenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dteDataInicial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string dteDataFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int intCodGrupo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int intExportada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string numVersao;
        
        public getPublicacoesVRequest()
        {
        }
        
        public getPublicacoesVRequest(string strUsuario, string strSenha, string dteDataInicial, string dteDataFinal, int intCodGrupo, int intExportada, string numVersao)
        {
            this.strUsuario = strUsuario;
            this.strSenha = strSenha;
            this.dteDataInicial = dteDataInicial;
            this.dteDataFinal = dteDataFinal;
            this.intCodGrupo = intCodGrupo;
            this.intExportada = intExportada;
            this.numVersao = numVersao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPublicacoesVResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getPublicacoesVResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.listaPublicacao getPublicacoesVResult;
        
        public getPublicacoesVResponse()
        {
        }
        
        public getPublicacoesVResponse(ServiceReference1.listaPublicacao getPublicacoesVResult)
        {
            this.getPublicacoesVResult = getPublicacoesVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPublicacoes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getPublicacoesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strSenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dteDataInicial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string dteDataFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int intCodGrupo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int intExportada;
        
        public getPublicacoesRequest()
        {
        }
        
        public getPublicacoesRequest(string strUsuario, string strSenha, string dteDataInicial, string dteDataFinal, int intCodGrupo, int intExportada)
        {
            this.strUsuario = strUsuario;
            this.strSenha = strSenha;
            this.dteDataInicial = dteDataInicial;
            this.dteDataFinal = dteDataFinal;
            this.intCodGrupo = intCodGrupo;
            this.intExportada = intExportada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPublicacoesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getPublicacoesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.listaPublicacao getPublicacoesResult;
        
        public getPublicacoesResponse()
        {
        }
        
        public getPublicacoesResponse(ServiceReference1.listaPublicacao getPublicacoesResult)
        {
            this.getPublicacoesResult = getPublicacoesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPublicacoesNaoExportadasV", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getPublicacoesNaoExportadasVRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strSenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intCodGrupo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string numVersao;
        
        public getPublicacoesNaoExportadasVRequest()
        {
        }
        
        public getPublicacoesNaoExportadasVRequest(string strUsuario, string strSenha, int intCodGrupo, string numVersao)
        {
            this.strUsuario = strUsuario;
            this.strSenha = strSenha;
            this.intCodGrupo = intCodGrupo;
            this.numVersao = numVersao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPublicacoesNaoExportadasVResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getPublicacoesNaoExportadasVResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.listaPublicacao getPublicacoesNaoExportadasVResult;
        
        public getPublicacoesNaoExportadasVResponse()
        {
        }
        
        public getPublicacoesNaoExportadasVResponse(ServiceReference1.listaPublicacao getPublicacoesNaoExportadasVResult)
        {
            this.getPublicacoesNaoExportadasVResult = getPublicacoesNaoExportadasVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPublicacoesNaoExportadas", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getPublicacoesNaoExportadasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strSenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intCodGrupo;
        
        public getPublicacoesNaoExportadasRequest()
        {
        }
        
        public getPublicacoesNaoExportadasRequest(string strUsuario, string strSenha, int intCodGrupo)
        {
            this.strUsuario = strUsuario;
            this.strSenha = strSenha;
            this.intCodGrupo = intCodGrupo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPublicacoesNaoExportadasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getPublicacoesNaoExportadasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.listaPublicacao getPublicacoesNaoExportadasResult;
        
        public getPublicacoesNaoExportadasResponse()
        {
        }
        
        public getPublicacoesNaoExportadasResponse(ServiceReference1.listaPublicacao getPublicacoesNaoExportadasResult)
        {
            this.getPublicacoesNaoExportadasResult = getPublicacoesNaoExportadasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPublicacoesGrupo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class setPublicacoesGrupoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strSenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intCodGrupo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strPublicacoes;
        
        public setPublicacoesGrupoRequest()
        {
        }
        
        public setPublicacoesGrupoRequest(string strUsuario, string strSenha, int intCodGrupo, string strPublicacoes)
        {
            this.strUsuario = strUsuario;
            this.strSenha = strSenha;
            this.intCodGrupo = intCodGrupo;
            this.strPublicacoes = strPublicacoes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPublicacoesGrupoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class setPublicacoesGrupoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int setPublicacoesGrupoResult;
        
        public setPublicacoesGrupoResponse()
        {
        }
        
        public setPublicacoesGrupoResponse(int setPublicacoesGrupoResult)
        {
            this.setPublicacoesGrupoResult = setPublicacoesGrupoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPublicacoes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class setPublicacoesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strSenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strPublicacoes;
        
        public setPublicacoesRequest()
        {
        }
        
        public setPublicacoesRequest(string strUsuario, string strSenha, string strPublicacoes)
        {
            this.strUsuario = strUsuario;
            this.strSenha = strSenha;
            this.strPublicacoes = strPublicacoes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPublicacoesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class setPublicacoesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int setPublicacoesResult;
        
        public setPublicacoesResponse()
        {
        }
        
        public setPublicacoesResponse(int setPublicacoesResult)
        {
            this.setPublicacoesResult = setPublicacoesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstatisticasPublicacoes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getEstatisticasPublicacoesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strSenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dteData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int intCodGrupo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strTipoAgrupamento;
        
        public getEstatisticasPublicacoesRequest()
        {
        }
        
        public getEstatisticasPublicacoesRequest(string strUsuario, string strSenha, string dteData, int intCodGrupo, string strTipoAgrupamento)
        {
            this.strUsuario = strUsuario;
            this.strSenha = strSenha;
            this.dteData = dteData;
            this.intCodGrupo = intCodGrupo;
            this.strTipoAgrupamento = strTipoAgrupamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstatisticasPublicacoesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getEstatisticasPublicacoesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceReference1.estatisticasPublicacoes estatisticasPublicacoes;
        
        public getEstatisticasPublicacoesResponse()
        {
        }
        
        public getEstatisticasPublicacoesResponse(ServiceReference1.estatisticasPublicacoes estatisticasPublicacoes)
        {
            this.estatisticasPublicacoes = estatisticasPublicacoes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="waitSeconds", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class waitSecondsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intTempoSegundos;
        
        public waitSecondsRequest()
        {
        }
        
        public waitSecondsRequest(string strToken, int intTempoSegundos)
        {
            this.strToken = strToken;
            this.intTempoSegundos = intTempoSegundos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="waitSecondsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class waitSecondsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string waitSecondsResult;
        
        public waitSecondsResponse()
        {
        }
        
        public waitSecondsResponse(string waitSecondsResult)
        {
            this.waitSecondsResult = waitSecondsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface wsPublicacaoSoapChannel : ServiceReference1.wsPublicacaoSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class wsPublicacaoSoapClient : System.ServiceModel.ClientBase<ServiceReference1.wsPublicacaoSoap>, ServiceReference1.wsPublicacaoSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsPublicacaoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsPublicacaoSoapClient.GetBindingForEndpoint(endpointConfiguration), wsPublicacaoSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPublicacaoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsPublicacaoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPublicacaoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsPublicacaoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPublicacaoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getPublicacoesVResponse> getPublicacoesVAsync(ServiceReference1.getPublicacoesVRequest request)
        {
            return base.Channel.getPublicacoesVAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getPublicacoesResponse> getPublicacoesAsync(ServiceReference1.getPublicacoesRequest request)
        {
            return base.Channel.getPublicacoesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getPublicacoesNaoExportadasVResponse> getPublicacoesNaoExportadasVAsync(ServiceReference1.getPublicacoesNaoExportadasVRequest request)
        {
            return base.Channel.getPublicacoesNaoExportadasVAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getPublicacoesNaoExportadasResponse> getPublicacoesNaoExportadasAsync(ServiceReference1.getPublicacoesNaoExportadasRequest request)
        {
            return base.Channel.getPublicacoesNaoExportadasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.setPublicacoesGrupoResponse> setPublicacoesGrupoAsync(ServiceReference1.setPublicacoesGrupoRequest request)
        {
            return base.Channel.setPublicacoesGrupoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.setPublicacoesResponse> setPublicacoesAsync(ServiceReference1.setPublicacoesRequest request)
        {
            return base.Channel.setPublicacoesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getEstatisticasPublicacoesResponse> getEstatisticasPublicacoesAsync(ServiceReference1.getEstatisticasPublicacoesRequest request)
        {
            return base.Channel.getEstatisticasPublicacoesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.waitSecondsResponse> waitSecondsAsync(ServiceReference1.waitSecondsRequest request)
        {
            return base.Channel.waitSecondsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsPublicacaoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsPublicacaoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsPublicacaoSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.webjur.com.br/wsPublicacao.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsPublicacaoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.webjur.com.br/wsPublicacao.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsPublicacaoSoap,
            
            wsPublicacaoSoap12,
        }
    }
}
